apiVersion: v1
kind: ConfigMap
metadata:
  namespace: demo
  name: postgres-config
data:
  postgresql.conf: |
    max_connections = 300
    shared_buffers = 512MB
    log_statement = 'all'
    log_destination = 'stderr'
    logging_collector = on
    log_directory = '/var/lib/postgresql/data/log'
    log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
    log_rotation_age = 1d
    log_rotation_size = 100MB

  pg_hba.conf: |
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    local   all             all                                     trust
    host    all             all             127.0.0.1/32            md5
    host    all             all             ::1/128                 md5
    host    all             all        0.0.0.0/0               md5
